# -*- coding: utf-8 -*-
"""hw1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18sVPU63Ype8XmOe0cCoCCUXb9jxT1NL2
"""

print("請輸入您的身高(公尺)和體重(公斤)")
m = float(input())
kg = float(input())
print("您的BMI是",end=":")
print(kg/(m**2))