# -*- coding: utf-8 -*-
"""1018_回家作業.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m9teLwuF18kx7lWpyp-Sf61vHF69ME5v

Ｑ：模擬圖書館的書籍管理系統，讓使用者可藉由輸入書本名稱＆作者查找書籍

程式應包含以下操作：


1.   允許用戶可選擇四項功能：列印所有書籍、添加書籍、查詢書籍、結束。
2.   創建一個空的書籍列表，每本書籍包含書名、作者和出版年份等資訊。
1.   使用迭代器列印所有書籍的資訊。
2.   使用 itertools 模組中的函式將書籍列表按書名或作者名進行分組。
1.   允許用戶查詢特定書籍的資訊，讓使用者可藉由輸入書本名稱＆作者查找書籍。

## **請勿刪除註解及修改配分**
# 請依據提示完成程式碼，勿修改變數名稱
"""
import re
import itertools
# 請import需要使用的相關套件(10%)
'''
略
'''

def main():
    # 創建新的書籍列表，每本書籍包含書名、作者和出版年份等資訊(5%)

    library = []

    while True:
        print("選項：")
        print("1. 列印所有書籍")
        print("2. 添加新書籍")
        print("3. 查詢書籍")
        print("4. 結束")
        option = input("輸入選項： ")

        if option == '1':
            print("\n所有書籍資訊：")
            # 使用 itertools 模組中的分組函式，讓使用者可以選擇將書籍列表按書名或作者名印出(40%)
            group = input("按書名 (N) 還是按作者 (A) 分組: ")
            if group == "N":
                key_func = lambda book:book.split(',')[0]
            elif group == "A":
                key_func = lambda book:book.split(',')[1]
            else:
                print("無效選項。請重新輸入。\n")
                continue
            sorted_library = sorted(library,key=key_func)
            grouped_library = itertools.groupby(sorted_library,key_func)
            for key, group in grouped_library:
                print(f"分组：{key}")
                for book in group:
                    print(book)

        elif option == '2':
            # 使用re模組檢查書名和作者只能包含字母和空格(10%)
            book_title = input("輸入書名： ")
            if re.match(r"[A-Za-z]",book_title) == None:
                print("錯誤的書名")
                continue
            else:
                book_author = input("輸入作者： ")
                if re.match(r"[A-Za-z]",book_author) == None:
                    print("錯誤的作者姓名")
                    continue
                else:
                    book_year = input("輸入出版年份： ")
            book_info = f"書名: {book_title}, 作者: {book_author}, 出版年份: {book_year}"
            library.append(book_info)
            print("書籍已添加。\n")

        elif option == '3':
            # 使用re模組檢查書名和作者只能包含字母和空格(10%)
            search_title = input("輸入要查詢的書名： ")
            if re.match(r"[A-Za-z]",search_title) == None:
                print("錯誤的書名")
                continue
            else:
                search_author = input("輸入要查詢的作者： ")
                if re.match(r"[A-Za-z]",search_author) == None:
                    print("錯誤的作者姓名")
                    continue
            
            found_books = [book for book in library if re.search(f'書名: .*{search_title}.* 作者: .*{search_author}.*', book)]# 將找到的書籍用list綜合表達式呈現，請完成[]中的程式碼(15%)

            if len(found_books) != 0:
                print("\n查詢結果：")
                # 使用for迴圈，將找到的書籍印出來(10%)
                for i in found_books:
                    print(i)
            else:
                print("未找到符合條件的書籍。\n")

        elif option == '4':
            break
        else:
            print("無效選項。請重新輸入。\n")

if __name__ == "__main__":
    main()